name: GraMi Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with Gradle
        run: ./gradlew test --tests queryGenerator.* --tests configuration.*
      - name: Build libs and distributions with Gradle
        run: ./gradlew build -x test
      - name: Upload libs
        uses: actions/upload-artifact@v2
        with:
          name: grami-libs
          path: build/libs
      - name: Upload distributions
        uses: actions/upload-artifact@v2
        with:
          name: grami-dist
          path: build/distributions
